### ISSUE TITLE
Assignment 2: Comments

### ISSUE THREAD

**Issue by Ameya05** [airavata-courses/SinghPrasandeep#11]
Hey,

I could verify your RMQ and Docker setup from the code, looks good to me.
I am trying to use the application at http://129.114.17.180:8000/ , but there seems to be no response. After checking the RMQ at http://129.114.17.180:15672/ , the messages are still in the Queue, so probably your microservices are not up and running? Can you please check on this ?

Another thing is can you give me some details on how Jenkins is setup at the moment and email me the Jenkins credentials so that I can take a look at it.

**Comment by singhPrasan** [comment]
Hi @Ameya05 ,

 1) http://129.114.17.180:8000/, this link is working fine for me. I double checked it on a separate machine and it still works. Could you please give it a second try?

2) The messages were still in the queue because they weren't removed. Currently, the python microservice is configured to send and receive one message per click. So, in order to retrieve all messages from the queue, you would have to click on the receive button multiple times. Moreover, RabbitMQ updates the messages a bit late, so you might have to do a hard refresh to see the sent/received count update.

3) I checked and found that node microservice is not up. There is a bug while creating the docker image. I'm looking into it.

4) For Jenkins, I have set up 3 branches ( microservice1, microservice2, and gateway-server) and configured them to auto build whenever a commit is made to the respective branch. I have emailed you the Jenkins credentials for cross verification.

**Comment by Ameya05** [comment]
Sorry, I didn't phrase it out properly. I meant to say that I am using the application at http://129.114.17.180:8000/ , but when I click the **Send from Python** button and then click the **Receive** button next to that, there is no response / change on the page. 
I am entering some random text in the text box and clicking the send button, is this the correct use case? 

![Screenshot](https://user-images.githubusercontent.com/21273628/30778991-07f8761c-a0b1-11e7-8d2c-0a9267669cef.JPG)

**Comment by singhPrasan** [comment]
@Ameya05, Thanks for providing the screenshot. I tried the issue you are getting and was able to replicate it. I'm not sure about the reason behind this, but once you click on send and you don't see a confirmation text, click on the receive button. After clicking on receive button, you will be able to see both the sent and received confirmation. After this initial step, send and receive will work as expected. 
Please try this and let me know if the issue still persists.

**Comment by Ameya05** [comment]
I was able to run it once, so marking this as reviewed!
Looks like the gateway / application bugs out in subsequent request attempts.
